
dist: trusty
sudo: false 

language: python

addons:
  apt:
    packages:
    - python-numpy

python: 
  - "2.7"
  - "3.6"
  
install:
    
    - pip install -U pynwb
    - pip install runipy
    - pip install pyabf
    - pip install imageio
script:
    - cd NWB
    - python simple.py
    - python time_series_data.py
    - ls -alt
    
    - cd ../FergusonEtAl2015/
    - runipy TestData.ipynb 
    - ls -alt
    
    - cd ../TriplettEtAl2018
    - runipy TestDataset.ipynb 
    - ls -alt
    
    - cd ../ScholzEtAl2019
    - wget https://osf.io/5298q/download -O AML18_moving.hdf5  
    - wget https://osf.io/sgnrh/download -O AML175_moving.hdf5  
    - runipy Testing.ipynb 
    - ls -alt
    
