
dist: trusty
sudo: false 

language: python

addons:
  apt:
    packages:
    - python-numpy

python: 
  - "2.7"
  - "3.6"
  
install:
    
    - pip install -U pynwb
    - pip install runipy
    
script:
    - cd NWB
    - python simple.py
    - python time_series_data.py
    - ls -alt
    
    - cd ../FergusonEtAl2015/
    - runipy TestData.ipynb 
    - ls -alt
